server:
  port: 9090

spring:
  application:
    name: spring-boot-keycloak-security

keycloak:
  realm: employee-service
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: spring-keycloak-client
  public-client: true
  bearer-only: true
  credentials:
    secret: Client-Secret
    username: YOUR_REALM_ADMIN_USERNAME
    password: Your_REALM_ADMIN_PASSWORD
    provider: secret


